# Generated by Django 2.2.12 on 2020-12-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_subscriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptions',
            old_name='user',
            new_name='subscribed_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stripe_id',
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
