# Generated by Django 2.2.12 on 2020-12-17 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20201216_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptions',
            old_name='stripe_id',
            new_name='token',
        ),
    ]
