# Generated by Django 2.2.12 on 2020-12-29 05:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20201217_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='token',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
