# Generated by Django 2.2.12 on 2020-12-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20201229_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='token',
            field=models.CharField(max_length=500),
        ),
    ]
