# Generated by Django 2.2.12 on 2021-01-01 14:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20201229_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='charge',
            field=models.DecimalField(decimal_places=2,  max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='created_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='subscribed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
