# Generated by Django 2.2.12 on 2021-01-06 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20210101_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'verbose_name_plural': 'subscribers'},
        ),
        migrations.RemoveField(
            model_name='subscriptions',
            name='charge',
        ),
        migrations.RemoveField(
            model_name='subscriptions',
            name='token',
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
