# Generated by Django 2.2.12 on 2021-01-06 09:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20210106_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=8),
            preserve_default=False,
        ),
    ]
