# Generated by Django 2.2.12 on 2021-01-07 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_subscriptions_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='subscribed_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
