# Generated by Django 2.2.12 on 2021-01-07 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_auto_20210107_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptions',
            old_name='subscribed_by',
            new_name='subscribed',
        ),
    ]
