# Generated by Django 2.2.12 on 2021-01-07 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_auto_20210107_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptions',
            old_name='subscribed',
            new_name='subscriber',
        ),
    ]
