# Generated by Django 2.2.10 on 2020-03-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='avarta',
            field=models.URLField(blank=True, default='DEFAULT VALUE'),
        ),
    ]
